name: Core Library CI

on:
  push:
    paths:
      - "core/**"
      - ".github/workflows/core.yml"
  pull_request:
    paths:
      - "core/**"
      - ".github/workflows/core.yml"

jobs:
  test:
    name: Test and Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Format Check
        working-directory: ./core
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "The following files are not formatted:"
            gofmt -l .
            exit 1
          fi

      - name: Run Tests
        working-directory: ./core
        run: go test -v ./...
